import { useDeferredValue, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useSearchParams } from "react-router-dom";
import { getRecoveryPlans } from "@/api/recoveryAgentApi";
import { ErrorState } from "@/components/ErrorState";
import { LoadingState } from "@/components/LoadingState";
import { PageContainer } from "@/components/PageContainer";
import type { PlanSort } from "./utils";

const PAGE_SIZE = 20;

export function RecoveryPlansPage() {
  const [params] = useSearchParams();
  const [search, setSearch] = useState("");
  const [recommendation, setRecommendation] = useState(params.get("recommendation") ?? "");
  const [sort, setSort] = useState<PlanSort>(
    (params.get("sort") as PlanSort) ?? "created",
  );
  const [page, setPage] = useState(1);
  const deferredSearch = useDeferredValue(search);
  const query = useQuery({
    queryKey: ["recovery-agent", "plans", page, deferredSearch, recommendation, sort],
    queryFn: ({ signal }) => getRecoveryPlans({
      limit: PAGE_SIZE, offset: (page - 1) * PAGE_SIZE,
      search: deferredSearch, recommendation, sort,
    }, signal),
  });
  const visible = query.data?.plans ?? [];
  const total = query.data?.pagination.total ?? 0;
  return <PageContainer title="Recovery Plans" description="Every explainable plan generated by the Recovery Agent.">
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap gap-3 rounded-lg bg-surface p-4 shadow-elev-1">
        <input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search plans" className="h-10 flex-1 rounded-md border border-border bg-surface px-3 text-text" />
        <select value={recommendation} onChange={e => { setRecommendation(e.target.value); setPage(1); }} className="rounded-md border border-border bg-surface px-3 text-text">
          <option value="">All recommendations</option><option>Replace</option><option>Monitor</option><option>None</option>
        </select>
        <select value={sort} onChange={e => setSort(e.target.value as PlanSort)} className="rounded-md border border-border bg-surface px-3 text-text">
          <option value="created">Created</option><option value="confidence">Confidence</option><option value="media">Media</option><option value="recommendation">Recommendation</option>
        </select>
      </div>
      {query.isLoading ? <LoadingState label="Loading recovery plans" rows={8} /> : query.isError ? <ErrorState title="Plans unavailable" description="Recovery plans could not be loaded." /> :
      <div className="overflow-x-auto rounded-lg bg-surface shadow-elev-1"><table className="w-full min-w-[1100px] text-left text-body">
        <thead className="border-b border-border text-meta uppercase text-text-subtle"><tr>{["Plan ID","Media","Media Type","Current Health","Confidence","Recommendation","Status","Created","Duration","Actions"].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead>
        <tbody className="divide-y divide-border">{visible.map(plan => <tr key={plan.id}>
          <td className="p-3 font-mono text-meta">{plan.id}</td><td className="p-3">{plan.media_title ?? plan.torrent_hash}</td><td className="p-3 text-text-muted">{plan.media_type ?? "Unknown"}</td>
          <td className="p-3">{String(plan.current_health.status ?? "Unknown")}</td><td className="p-3 font-semibold">{plan.confidence.toFixed(0)}</td><td className="p-3">{plan.recommendation}</td>
          <td className="p-3">{plan.status}</td><td className="p-3">{new Date(plan.created_at).toLocaleString()}</td><td className="p-3">{plan.evaluation_duration_ms} ms</td>
          <td className="p-3"><Link className="font-semibold text-accent" to={`/recovery-agent/plans/${plan.id}`}>Inspect</Link></td>
        </tr>)}</tbody>
      </table></div>}
      <div className="flex items-center justify-between text-body text-text-muted"><span>{total} plans</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage(p => p - 1)} className="rounded-md border border-border px-3 py-1 disabled:opacity-40">Previous</button><span>Page {page}</span><button disabled={!query.data?.pagination.has_more} onClick={() => setPage(p => p + 1)} className="rounded-md border border-border px-3 py-1 disabled:opacity-40">Next</button></div></div>
    </div>
  </PageContainer>;
}
